version: "3.5"

services: 
  media_provider:
    # this equates to:
    # build:
    #   context: ./src/service/media-info-provider
    #   dockerfile: Dockerfile
    build: ./src/service/media-info-provider
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: 5000
    env_file:
      - ./src/service/media-info-provider/.env
    volumes: 
      - ./src/service/media-info-provider/src:/app/src
    ports: 
      - 5000:5000
    # TODO: maybe it can be reused in production environment
    # secrets:
    #   - TMDB_API_KEY
  user_account_service:
    build: ./src/service/user-account-service
    environment: 
      CHOKIDAR_USEPOLLING: "true"
      PORT: 5001:5001
    env_file:
      - ./src/service/user-account-service/.env
    volumes:
      - ./src/service/user-account-service/src:/app/src
    ports: 
      - 5001
  user_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  react_frontend:
    build:
      context: ./src/client\web-react
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: 3000
    volumes:
      - ./src/client/web-react/src:/app/src
      - ./src/client/web-react/public:/app/public
    ports:
      - 3000:3000

volumes:
  mongodb_data_container:
# secrets:
#   TMDB_API_KEY:
#     external: true